export const partnerConstants = {

  FETCH_ALL_REQUEST: 'PARTNER_FETCH_ALL_REQUEST',
  FETCH_ALL_SUCCESS: 'PARTNER_FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'PARTNER_FETCH_ALL_FAILURE',

  FETCH_REQUEST: 'PARTNER_FETCH_REQUEST',
  FETCH_SUCCESS: 'PARTNER_FETCH_SUCCESS',
  FETCH_FAILURE: 'PARTNER_FETCH_FAILURE',

};
